apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachine
metadata:
  name: test-machine-with-dynamic-host
  namespace: default
spec:
  instanceType: m5.large
  ami:
    id: ami-0abcdef1234567890
  iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
  
  # Dynamic dedicated host allocation configuration
  dynamicHostAllocation:
    # Instance family for the dedicated host (required)
    instanceFamily: "m5"
    
    # Specific instance type for the host (optional, derived from instanceFamily if not specified)
    instanceType: "m5.large"
    
    # Number of dedicated hosts to allocate (optional, defaults to 1)
    quantity: 1
    
    # Target availability zone (optional, uses instance subnet's AZ if not specified)
    availabilityZone: "us-west-2a"
    
    # Whether to automatically release the host when machine is deleted (optional, defaults to true)
    autoRelease: true
    
    # Tags to apply to the allocated dedicated host (optional)
    tags:
      Environment: "production"
      Application: "virtualization"
      CostCenter: "engineering"
      Purpose: "BYOL-Windows"

  # Standard instance configuration
  subnet:
    id: subnet-0a1b2c3d4e5f6g7h8
  
  securityGroupOverrides:
    - id: sg-0123456789abcdef0
  
  userData:
    name: test-userdata
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: test-userdata
  namespace: default
type: Opaque
data:
  userData: IyEvYmluL2Jhc2gKZWNobyAiSGVsbG8gV29ybGQi  # base64 encoded "#!/bin/bash\necho \"Hello World\""